Clean up node_module imports
unic/estatico pull request #23
Opened 2016-11-29 14:45 UTC by caillou

The `main` property of a module's `package.json` tells you, what
module will be imprted.

In the case of `jQuery`, the `package.json` reads:

```
{
  ...
  "main": "dist/jquery.js",
  ...
}
```

So the following lines are equivalent:

```
import $ from 'jquery'
import $ from 'jquery/dist/jquery'
```

2016-11-29 19:23 UTC, backflip commented on gulp/js/default.js
> -					handlebars: 'handlebars/runtime.js'
I'd keep this in order to allow for `const handlebars = require('handlebars')` and `import handlebars from 'handlebars'`, respectively.

2016-11-29 19:34 UTC, backflip commented on gulp/js/default.js
> -					handlebars: 'handlebars/runtime.js'
Which is ironic since we still worked around this with `import '../../../node_modules/handlebars/dist/handlebars';`in `main.js`.

2016-11-29 19:36 UTC, backflip commented on source/assets/js/main.js
> -import '../../../node_modules/handlebars/dist/handlebars';
You can remove this since `handlebars-loader` will already include the runtime. This will reduce the generated JavaScript by about 80kb… Sorry about this, pretty ugly bug.

2016-11-29 20:23 UTC, backflip commented
Thanks a lot for this!
Two suggestions above (one only partly related to the change).

2016-12-07 13:39 UTC, backflip commented
@caillou, what's your opinion on the proposed changes?

2016-12-09 12:11 UTC, caillou commented
@backflip I think, we should not do the handlebars alias. if you start treating some node packages differently than others, it just introduces confusion. But that is my opinion. Also, I do not intend to spend more time on this PR, I don't mind if you want to change it. I trust that you'll take the right decision. ❤️

2016-12-16 21:13 UTC, backflip commented
@caillou, I just remembered the reason for this: If we want to use our handlebars helpers config universally, we *have* to alias `handlebars` to `handlebars/runtime` since it already registers them and returns a handlebars instance. However, it would probably make sense to just return helper methods instead of already registering them with a handlebars instance.

2017-01-25 16:44 UTC, orioltf requested changes
@backflip Out of your comment I think that an alias should be re-added, right? Can you review this PR again, please?

2017-01-25 16:52 UTC, backflip commented
@orioltf Let's merge and re-add it in a second PR.

2017-01-25 16:53 UTC, merged