Updating jQuery to 3.1.1
unic/estatico pull request #45
Opened 2017-02-11 09:11 UTC by marbor3

Updating jQuery to the latest.
Right now found only two breaking changes - `$(document).on('ready'` removal and `data()` not returning  requested whole data object when data attribute name is in kebab-case.

Full list of changes and a migration guide:
https://jquery.com/upgrade-guide/3.0/

2017-03-24 16:53 UTC, orioltf requested changes
I'd have a look at these 2 little things. otherwise the upgrade seems good :)

2017-03-24 16:53 UTC, orioltf commented on source/assets/js/helpers/estaticoapp.js
> +		// jQuery 3 does not support `ready` event in $(document).on() https://jquery.com/upgrade-guide/3.0/#breaking-change-on-quot-ready-quot-fn-removed
We should then remove the `ready` event from the [`module`](https://github.com/unic/estatico/pull/45/files#diff-bd637ae4c8e9321feb7e1d08e3ca0ed2R34) file, shouldn't we?

2017-03-24 16:53 UTC, orioltf commented on package.json
> +    "jquery": "3.1.1",
In the meantime jQuery went up to v3.2.0. We should fix that right before finally having green light

2017-04-21 10:56 UTC, marbor3 commented on source/assets/js/helpers/estaticoapp.js
> +		// jQuery 3 does not support `ready` event in $(document).on() https://jquery.com/upgrade-guide/3.0/#breaking-change-on-quot-ready-quot-fn-removed
Not really - I still would keep module initialisation on some kind of event - so sending ready info like it was before - just now the info is just plain Object `{type: 'ready'}` to fit into other events sent later.

2017-05-05 14:41 UTC, orioltf commented
Hi @marbor3 the Unit test from Slideshow fails. Could you have a look at it, please?

2017-06-08 18:18 UTC, backflip commented
@orioltf, same issue as in https://github.com/unic/estatico/pull/64#issuecomment-307172434
Rebasing fixed the issue for me.

2017-06-08 18:19 UTC, backflip approved these changes

2017-06-08 18:21 UTC, merged