Feature/partial listing
unic/estatico pull request #55
Opened 2017-03-09 15:51 UTC by swey

This PR is an addition to https://github.com/unic/estatico/pull/54

Additionally to linking the used sub module, this change will also list all used partials (which are no own module). Looks like this:
![bildschirmfoto 2017-03-09 um 16 47 27](https://cloud.githubusercontent.com/assets/568574/23757956/854073a0-04e8-11e7-87b6-9e4c757f88a9.png)

2017-03-24 14:18 UTC, orioltf approved these changes

2017-03-24 17:04 UTC, orioltf requested changes

2017-03-24 17:04 UTC, orioltf commented on helpers/data.js
> +		function highlightTemplateCode(content) {
Can we have this function either in the main scope (like `getTemplateCode` or `getUsedPartialsInTemplate`)?

2017-03-28 18:12 UTC, swey commented
@orioltf Please re-check (Also made those new methods `private`)

2017-05-05 16:01 UTC, orioltf commented
Hi @swey would you mind resolving the conflicts, please? Thanks!

2017-05-05 19:22 UTC, swey commented
Next try :)

2017-05-08 07:00 UTC, orioltf approved these changes

2017-05-08 07:00 UTC, merged