[Feature] Gulp: Validate node.js version before running
unic/estatico pull request #8
Opened 2016-10-09 12:45 UTC by d-simon

2016-11-01 19:13 UTC, backflip commented
Could you rebase this on develop? There was some force-pushing happening for v5.0.0.

![yolo](http://i.giphy.com/bcXoQSO8lx7tm.gif)

2016-11-02 13:07 UTC, 0xfffxfff commented
"Rebase"

![really_a_pony_version_of_a_meme_some_bronies_really_2fb4eedd3de7d2f02ac5b5b683891f6d-1](https://cloud.githubusercontent.com/assets/21964126/19929833/b4019760-a105-11e6-8e24-d304bbe0f156.jpg)

2016-11-02 13:16 UTC, d-simon commented
"Rebase"
![really_a_pony_version_of_a_meme_some_bronies_really_2fb4eedd3de7d2f02ac5b5b683891f6d-1](https://cloud.githubusercontent.com/assets/5261748/19930066/eb3f176a-a106-11e6-909f-cc7c44406f8e.jpg)

2016-11-02 13:30 UTC, backflip commented
`alias rebase` = `git reset --hard origin/develop && git cherry-pick 67319ca6ed0c8d6d174f4899c49763e2bd4f6765 && git push -f`

2016-11-02 13:51 UTC, backflip commented
LGTM

2017-01-25 16:25 UTC, orioltf requested changes
@d-simon would you mind doing the rebase in your branch, please? Nothing else is missing to get green light here! #gogogo

2017-01-25 16:28 UTC, d-simon commented
@orioltf great to hear. It saved one of our devs many times.
IIRC there is a Rebase&Merge button in gh now. No? 😜 Otherwise I can rebase it tomorrow.

2017-01-25 17:16 UTC, d-simon commented
Ah I didn't see the conflicts from mobile. Well, I had to remove the `npm-shrinkwrap.json` because I wasn't able to get into a conflict free state. @orioltf @backflip Is there a reason we still keep a shrinkwrap json file instead of `yarn.lock`?

2017-01-25 18:06 UTC, orioltf commented
@d-simon You can have a look at issue #12 However, I bet your comment was meant to be an upcoming PR, right?! 😝

2017-02-10 15:14 UTC, backflip commented
Replaced with https://github.com/unic/estatico/pull/44 with a regenerated `npm-shrinkwrap.json`

2017-02-10 15:14 UTC, closed without merging